// Generated by CoffeeScript 1.8.0
(function() {
	var fs, http, server;

	fs = require('fs');

	http = require('http');

	server = http.Server(function(req, res) {
		return res.writeHead(200);
	});

	server.listen(8080);

}).call(this);